Have 10j automatically provision itself

diff --git a/cli/10j b/cli/10j
--- a/cli/10j
+++ b/cli/10j
@@ -14,9 +14,18 @@ rootdir=$(dirname "$tenjdir")
 localuv="${rootdir}/_local/uv"
 localcg="${rootdir}/_local/uv.toml"
 
+if [ ! -e "$localuv" ] || [ ! -e "$localcg" ]; then
+    sh "$tenjdir/sh/provision.sh" uv
+
+    if [ "$1" = "" ]; then
+        echo 'Please run `10j provision` to continue setup.'
+        exit 0
+    fi
+fi
+
 if [ -e "$localuv" ] && [ -e "$localcg" ]; then
     exec "$localuv" run --project "$tenjdir" --config-file "$localcg" $tenjdir/main.py "$@"
 else
-    echo "Before running 10j, please run     sh cli/sh/provision.sh" >&2
+    echo "10j's provisioning failed -- sorry!" >&2
     exit 1
 fi
