Combine OCaml job/cache into test job
End-to-end tests require a fully provisioned setup. With caching, provisioning
OCaml and CodeHawk only takes ~15 seconds. The other 20-30 seconds in
the OCaml job was spent provisioning LLVM etc.

This change also allows us to eliminate a somewhat hacky workaround for
caching CodeHawk before the `_local` directory existed.

diff --git a/.github/workflows/nrsr.yaml b/.github/workflows/nrsr.yaml
--- a/.github/workflows/nrsr.yaml
+++ b/.github/workflows/nrsr.yaml
@@ -35,7 +35,7 @@ jobs:
       - name: Code linting and formatting checks
         run: cli/10j check-py
 
-  not-rocket-science-rs-test:
+  not-rocket-science-tests:
     strategy:
       fail-fast: false
       matrix:
@@ -43,6 +43,9 @@ jobs:
     runs-on: ${{ matrix.runner }}
     env:
       C2RUST_TESTED_CRATES: "-p c2rust -p c2rust-transpile -p c2rust-ast-printer"
+    defaults:
+      run:
+        shell: bash # GitHub Actions applies pipefail only for explicitly requested bash shell.
     steps:
       - uses: actions/checkout@v4
       - uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2.8.0
@@ -53,17 +56,61 @@ jobs:
           cache-workspace-crates: true
           save-if: ${{ github.ref == 'refs/heads/main' }}
 
+      - name: Install tss utility for showing timestamps
+        run: |
+          loweros=$(uname -s | tr '[:upper:]' '[:lower:]')
+          curl --silent --location --output tss https://github.com/kevinburke/tss/releases/download/1.3/tss-${loweros}-amd64 && chmod +x tss
+
       - name: Provision Rust
-        run: cli/10j provision rust
+        run: cli/10j provision rust 2>&1 | ./tss
 
       - name: Build c2rust tests
-        run: cd c2rust && ../cli/10j cargo test --locked --release $C2RUST_TESTED_CRATES --no-run
+        run: cd c2rust && ../cli/10j cargo test --locked --release $C2RUST_TESTED_CRATES --no-run 2>&1 | ../tss
 
       - name: Run c2rust unit tests
-        run: cd c2rust && ../cli/10j cargo test --locked --release $C2RUST_TESTED_CRATES
+        run: cd c2rust && ../cli/10j cargo test --locked --release $C2RUST_TESTED_CRATES 2>&1 | ../tss
 
       - name: Build c2rust binaries
-        run: XJ_BUILD_RS_PROFILE=release cli/10j build-rs
+        run: XJ_BUILD_RS_PROFILE=release cli/10j build-rs 2>&1 | ./tss
+
+      - name: Extract OCaml Cache Keys
+        id: extract
+        run: |
+          echo "ocaml_key=$(python3 cli/constants.py ocaml-cache-key)" >> $GITHUB_OUTPUT
+          echo "codehawk_key=$(python3 cli/constants.py codehawk-cache-key)" >> $GITHUB_OUTPUT
+
+      # We don't use setup-ocaml because it would compile OCaml in the runner's
+      # environment, which has libraries that aren't available to the 10j toolchain.
+      # Thus, when our provisioning process would try to compile dune, it would fail.
+      # This action restores a previous cache, if we have one, and populates the cache
+      # if the workflow succeeds.
+      # XREF:ci-opam-paths
+      - name: Cache OCaml
+        id: cache-ocaml
+        uses: actions/cache@v4
+        with:
+          path: |
+            ~/.opam
+            ~/.local/bin/opam
+          key: ${{ steps.extract.outputs.ocaml_key }}
+
+      # We cache CodeHawk separately because we expect it to change more frequently.
+      # CodeHawk-C is not cached because it embeds binaries built from CodeHawk,
+      # and is otherwise just a source checkout with no build step.
+      - name: Cache CodeHawk
+        id: cache-codehawk
+        uses: actions/cache@v4
+        with:
+          path: |
+            _local/codehawk
+          key: ${{ steps.extract.outputs.codehawk_key }}
+
+      - name: Provision OCaml
+        run: cli/10j provision ocaml 2>&1 | ./tss
+
+      - name: Run Tenjin end-to-end tests
+        run: cli/10j check-e2e-smoke-tests 2>&1 | ./tss
+
 
   not-rocket-science-rs-lint:
     runs-on: ubuntu-latest
@@ -95,47 +142,4 @@ jobs:
 
       - name: Code linting and formatting checks
         run: CMAKE_CXX_COMPILER_LAUNCHER=ccache cli/10j check-rs |& ./tss
-        shell: bash  # GitHub Actions applies pipefail only for explicitly requested bash shell.
-
-  not-rocket-science-ocaml:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
-
-      - name: Extract OCaml Cache Keys
-        id: extract
-        run: |
-          echo "ocaml_key=$(python3 cli/constants.py ocaml-cache-key)" >> $GITHUB_OUTPUT
-          echo "codehawk_key=$(python3 cli/constants.py codehawk-cache-key)" >> $GITHUB_OUTPUT
-
-      # We don't use setup-ocaml because it would compile OCaml in the runner's
-      # environment, which has libraries that aren't available to the 10j toolchain.
-      # Thus, when our provisioning process would try to compile dune, it would fail.
-      # This action restores a previous cache, if we have one, and populates the cache
-      # if the workflow succeeds.
-      # XREF:ci-opam-paths
-      - name: Cache OCaml
-        id: cache-ocaml
-        uses: actions/cache@v4
-        with:
-          path: |
-            ~/.opam
-            ~/.local/bin/opam
-          key: ${{ steps.extract.outputs.ocaml_key }}
-
-      # We don't cache CodeHawk in the `_local` directory because that doesn't exist yet.
-      # Instead, we cache it elsewhere, and provisioning moves it into place.
-      - name: Cache CodeHawk
-        id: cache-codehawk
-        uses: actions/cache@v4
-        with:
-          path: |
-            ~/.xj-cached-codehawk
-          key: ${{ steps.extract.outputs.codehawk_key }}
-
-      - name: Install tss utility for showing timestamps
-        run: curl --silent --location --output tss https://github.com/kevinburke/tss/releases/download/1.3/tss-linux-amd64 && chmod +x tss
-
-      - name: Provision OCaml
-        run: cli/10j provision ocaml |& ./tss
         shell: bash  # GitHub Actions applies pipefail only for explicitly requested bash shell.
